In [60]:
import pandas as pd
import numpy as np

In [61]:
dataset= pd.read_csv('IMDb Movies.csv')
dataset.head()

c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3155: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,None,Alexander Black,...,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,5.9,154,NaN,NaN,NaN,NaN,1.0,2.0
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,None,Charles Tait,...,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,589,$ 2250,NaN,NaN,NaN,7.0,7.0
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,...,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,5.8,188,NaN,NaN,NaN,NaN,5.0,2.0
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,...,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,446,$ 45000,NaN,NaN,NaN,25.0,3.0
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",...,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237,NaN,NaN,NaN,NaN,31.0,14.0

In [62]:
dataset = dataset.loc[(dataset.year==2018)|(dataset.year==2019)|(dataset.year==2020)]

In [63]:
dataset

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
15675,tt0069049,L'altra faccia del vento,The Other Side of the Wind,2018,2018-11-02,Drama,122,"France, Iran, USA","English, German",Orson Welles,...,"John Huston, Oja Kodar, Peter Bogdanovich, Sus...",A Hollywood director emerges from semi-exile w...,6.8,5887,NaN,NaN,NaN,78.0,81.0,98.0
43366,tt0360556,Fahrenheit 451,Fahrenheit 451,2018,2018-05-20,"Drama, Sci-Fi, Thriller",100,USA,English,Ramin Bahrani,...,"Michael B. Jordan, Aaron Davis, Cindy Katz, Mi...","In a terrifying care-free future, a young man,...",4.9,16882,NaN,NaN,NaN,NaN,206.0,74.0
44619,tt0385887,Motherless Brooklyn - I segreti di una città,Motherless Brooklyn,2019,2019-11-07,"Crime, Drama, Mystery",144,USA,"English, French",Edward Norton,...,"Edward Norton, Gugu Mbatha-Raw, Alec Baldwin, ...","In 1950s New York, a lonely private detective ...",6.8,34759,$ 26000000,$ 9277736,$ 18477736,60.0,319.0,178.0
46337,tt0427543,A Million Little Pieces,A Million Little Pieces,2018,2019-12-06,Drama,113,USA,English,Sam Taylor-Johnson,...,"Aaron Taylor-Johnson, Billy Bob Thornton, Odes...",A drug dependent young man faces his past and ...,6.2,1551,NaN,NaN,$ 89825,45.0,36.0,23.0
46723,tt0437086,Alita - Angelo della battaglia,Alita: Battle Angel,2019,2019-02-14,"Action, Adventure, Sci-Fi",122,"USA, Japan, Canada","English, Spanish",Robert Rodriguez,...,"Rosa Salazar, Christoph Waltz, Jennifer Connel...","A deactivated cyborg is revived, but cannot re...",7.3,217183,$ 170000000,$ 85710210,$ 404852543,53.0,2757.0,368.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65141,tt2181855,Cetiri ruze,Cetiri ruze,2019,2019-12-05,"Crime, Drama",100,Serbia,Serbian,Vasilije Nikitovic,...,"Milos Samolov, Boris Milivojevic, Srdjan 'Zika...",The film takes place in Belgrade within the co...,6.9,620,NaN,NaN,$ 181069,NaN,12.0,4.0
65331,tt2197936,Fatima,Fatima,2020,2020-08-28,Drama,113,"Portugal, USA",English,Marco Pontecorvo,...,"Joaquim de Almeida, Goran Visnjic, Stephanie G...","Based on historical events, three young shephe...",6.3,479,NaN,NaN,$ 128270,52.0,26.0,14.0
65354,tt2201211,A Boy Called Sailboat,A Boy Called Sailboat,2018,2019-05-06,"Comedy, Drama, Family",92,"USA, Australia","English, Spanish",Cameron Nugent,...,"J.K. Simmons, Keanu Wilson, Julian Atocani San...",A Hispanic family find hope in their extraordi...,6.7,965,NaN,NaN,NaN,NaN,30.0,11.0
65382,tt2205762,Model Home,Model Home,2018,2018-08-25,"Drama, Horror, Mystery",82,USA,English,Patrick Cunningham,...,"Monique Gabriela Curnen, Kathy Baker, Luke Gan...",A single mother entertains a dangerous fantasy...,4.1,175,NaN,NaN,NaN,NaN,4.0,7.0
65510,tt2222052,My Salinger Year,My Salinger Year,2020,2020-11-20,Drama,101,"Canada, Ireland",English,Philippe Falardeau,...,"Margaret Qualley, Sigourney Weaver, Douglas Bo...",A college grad takes a clerical job working fo...,6.0,154,NaN,NaN,NaN,44.0,3.0,19.0

In [64]:
dataset = dataset[['director','actors','genre','title']]

In [65]:
dataset.isna().sum()

director    9
actors      5
genre       0
title       0
dtype: int64

In [66]:
dataset = dataset.dropna()

In [67]:
actor_1_name=[]
actor_2_name=[]
actor_3_name=[]
for actor in dataset['actors']:
    if(len(actor.split(','))<1):
        actor_1_name.append('Unknown')
        actor_2_name.append('Unknown')
        actor_3_name.append('Unknown')
    elif(len(actor.split(','))<2):
        actor_1_name.append(actor.split(',')[0])
        actor_2_name.append('Unknown')
        actor_3_name.append('Unknown')
    elif(len(actor.split(','))<3):
        actor_1_name.append(actor.split(',')[0])
        actor_2_name.append(actor.split(',')[1])
        actor_3_name.append('Unknown')
    else:
        actor_1_name.append(actor.split(',')[0])
        actor_2_name.append(actor.split(',')[1])
        actor_3_name.append(actor.split(',')[2])

In [68]:
dataset['actor_1_name'] = actor_1_name
dataset['actor_2_name'] = actor_2_name
dataset['actor_3_name'] = actor_3_name

In [69]:
dataset

,director,actors,genre,title,actor_1_name,actor_2_name,actor_3_name
15675,Orson Welles,"John Huston, Oja Kodar, Peter Bogdanovich, Sus...",Drama,L'altra faccia del vento,John Huston,Oja Kodar,Peter Bogdanovich
43366,Ramin Bahrani,"Michael B. Jordan, Aaron Davis, Cindy Katz, Mi...","Drama, Sci-Fi, Thriller",Fahrenheit 451,Michael B. Jordan,Aaron Davis,Cindy Katz
44619,Edward Norton,"Edward Norton, Gugu Mbatha-Raw, Alec Baldwin, ...","Crime, Drama, Mystery",Motherless Brooklyn - I segreti di una città,Edward Norton,Gugu Mbatha-Raw,Alec Baldwin
46337,Sam Taylor-Johnson,"Aaron Taylor-Johnson, Billy Bob Thornton, Odes...",Drama,A Million Little Pieces,Aaron Taylor-Johnson,Billy Bob Thornton,Odessa Young
46723,Robert Rodriguez,"Rosa Salazar, Christoph Waltz, Jennifer Connel...","Action, Adventure, Sci-Fi",Alita - Angelo della battaglia,Rosa Salazar,Christoph Waltz,Jennifer Connelly
...,...,...,...,...,...,...,...
65141,Vasilije Nikitovic,"Milos Samolov, Boris Milivojevic, Srdjan 'Zika...","Crime, Drama",Cetiri ruze,Milos Samolov,Boris Milivojevic,Srdjan 'Zika' Todorovic
65331,Marco Pontecorvo,"Joaquim de Almeida, Goran Visnjic, Stephanie G...",Drama,Fatima,Joaquim de Almeida,Goran Visnjic,Stephanie Gil
65354,Cameron Nugent,"J.K. Simmons, Keanu Wilson, Julian Atocani San...","Comedy, Drama, Family",A Boy Called Sailboat,J.K. Simmons,Keanu Wilson,Julian Atocani Sanchez
65382,Patrick Cunningham,"Monique Gabriela Curnen, Kathy Baker, Luke Gan...","Drama, Horror, Mystery",Model Home,Monique Gabriela Curnen,Kathy Baker,Luke Ganalon
65510,Philippe Falardeau,"Margaret Qualley, Sigourney Weaver, Douglas Bo...",Drama,My Salinger Year,Margaret Qualley,Sigourney Weaver,Douglas Booth

In [70]:
dataset['genre'] = dataset['genre'].str.replace(',',' ')

In [71]:
director_ = []
for director in dataset['director']:
    director_.append(director.split(',')[0])

In [72]:
dataset['director'] = director_

In [73]:
dataset

,director,actors,genre,title,actor_1_name,actor_2_name,actor_3_name
15675,Orson Welles,"John Huston, Oja Kodar, Peter Bogdanovich, Sus...",Drama,L'altra faccia del vento,John Huston,Oja Kodar,Peter Bogdanovich
43366,Ramin Bahrani,"Michael B. Jordan, Aaron Davis, Cindy Katz, Mi...",Drama Sci-Fi Thriller,Fahrenheit 451,Michael B. Jordan,Aaron Davis,Cindy Katz
44619,Edward Norton,"Edward Norton, Gugu Mbatha-Raw, Alec Baldwin, ...",Crime Drama Mystery,Motherless Brooklyn - I segreti di una città,Edward Norton,Gugu Mbatha-Raw,Alec Baldwin
46337,Sam Taylor-Johnson,"Aaron Taylor-Johnson, Billy Bob Thornton, Odes...",Drama,A Million Little Pieces,Aaron Taylor-Johnson,Billy Bob Thornton,Odessa Young
46723,Robert Rodriguez,"Rosa Salazar, Christoph Waltz, Jennifer Connel...",Action Adventure Sci-Fi,Alita - Angelo della battaglia,Rosa Salazar,Christoph Waltz,Jennifer Connelly
...,...,...,...,...,...,...,...
65141,Vasilije Nikitovic,"Milos Samolov, Boris Milivojevic, Srdjan 'Zika...",Crime Drama,Cetiri ruze,Milos Samolov,Boris Milivojevic,Srdjan 'Zika' Todorovic
65331,Marco Pontecorvo,"Joaquim de Almeida, Goran Visnjic, Stephanie G...",Drama,Fatima,Joaquim de Almeida,Goran Visnjic,Stephanie Gil
65354,Cameron Nugent,"J.K. Simmons, Keanu Wilson, Julian Atocani San...",Comedy Drama Family,A Boy Called Sailboat,J.K. Simmons,Keanu Wilson,Julian Atocani Sanchez
65382,Patrick Cunningham,"Monique Gabriela Curnen, Kathy Baker, Luke Gan...",Drama Horror Mystery,Model Home,Monique Gabriela Curnen,Kathy Baker,Luke Ganalon
65510,Philippe Falardeau,"Margaret Qualley, Sigourney Weaver, Douglas Bo...",Drama,My Salinger Year,Margaret Qualley,Sigourney Weaver,Douglas Booth

In [74]:
dataset = dataset[['director','actor_1_name','actor_2_name','actor_3_name','genre','title']]

In [75]:
dataset = dataset.rename(columns={'genre':'genres'})
dataset = dataset.rename(columns={'title':'movie_title'})

In [76]:
dataset.head(20)

,director,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
15675,Orson Welles,John Huston,Oja Kodar,Peter Bogdanovich,Drama,L'altra faccia del vento
43366,Ramin Bahrani,Michael B. Jordan,Aaron Davis,Cindy Katz,Drama Sci-Fi Thriller,Fahrenheit 451
44619,Edward Norton,Edward Norton,Gugu Mbatha-Raw,Alec Baldwin,Crime Drama Mystery,Motherless Brooklyn - I segreti di una città
46337,Sam Taylor-Johnson,Aaron Taylor-Johnson,Billy Bob Thornton,Odessa Young,Drama,A Million Little Pieces
46723,Robert Rodriguez,Rosa Salazar,Christoph Waltz,Jennifer Connelly,Action Adventure Sci-Fi,Alita - Angelo della battaglia
46892,Kriv Stenders,Travis Fimmel,Toby Blome,Alexander England,Action Drama War,La battaglia di Long Tan
47132,David F. Sandberg,Zachary Levi,Mark Strong,Asher Angel,Action Adventure Comedy,Shazam!
49759,Todd Robinson,Sebastian Stan,Alison Sudol,Asher Miles Fallica,Drama War,Era mio figlio
49964,Jeff Tremaine,Machine Gun Kelly,Erin Ownbey,Douglas Booth,Biography Comedy Drama,The Dirt
50158,Gregor Jordan,Kelly Macdonald,Garrett Hedlund,David Wenham,Crime Drama Romance,Dirt Music
50603,Kevin Kölsch,Jason Clarke,Amy Seimetz,John Lithgow,Horror Mystery Thriller,Pet Sematary
50867,Dan Pritzker,Gary Carr,Erik LaRay Harvey,Ian McShane,Drama,Bolden
50877,Jay Chandrasekhar,Seann William Scott,Clifton Collins Jr.,Steve Lemme,Comedy Crime Mystery,Super Troopers 2
50907,Dain Said,Umie Aida,Faizal Hussein,Elyana,Horror Thriller,Dukun
51533,Tito da Costa,Sean Gray,Chris Blasman,Renee Dorian,Action Adventure Horror,Road to Red
51923,Alex Pettyfer,Jennifer Morrison,Nicola Peltz,Juliette Lewis,Crime Drama Thriller,Back Roads
52039,Jeff Wadlow,Michael Peña,Maggie Q,Lucy Hale,Action Adventure Fantasy,Fantasy Island
52244,Kannan Thamarakkulam,Jayaram,Sheelu Abraham,Ali,Drama,Pattabhiraman
52245,Dave Franco,Dan Stevens,Alison Brie,Sheila Vand,Horror Thriller,The Rental
52246,John Schultz,Rose McIver,Ben Lamb,Alice Krige,Family Romance,Un principe per Natale: Royal Baby

In [77]:
dataset.to_csv('movies_2018-2020.csv')